### ISSUE TITLE
MacMini 2018 - Boot key options not working

### ISSUE THREAD

**Issue by rolf-tx** [jetkvm/kvm#119]
On a mac (macmini 2018) the boot keys are not recognized.
I have tried: 
1) Left-Alt (Option)
2) LeftAlt + R

(Boot keys works with keyboard directly connected to the mac)

**Comment by Nevexo** [comment]
Potentially fixed in #113

**Comment by rolf-tx** [comment]
@Nevexo I tried jetkvm-next-7 app version but still no luck.

Why does the key show as: AltLeft, AltLeft ?
