### ISSUE TITLE
Update Error - Invalid TLS certificate

### ISSUE THREAD

**Issue by Eric-Schubert** [jetkvm/kvm#534]
Today, I installed JetKVM, started it, and let it load updates.

Now, when I access the web interface, I receive the following error message:

![Image](https://github.com/user-attachments/assets/b171ab6f-ef8c-4265-a2dc-8bb6deb359a0)

The same error message appears on the update screen as well:

![Image](https://github.com/user-attachments/assets/dfe04f32-445e-4faf-a0a8-721478c288a7)

I probably have the latest version, but the error message is still irritating.
There is no proxy or firewall blocking network traffic (the initial update ran without any problems)

The following version is currently installed:

![Image](https://github.com/user-attachments/assets/c4b97cdb-c8bb-405b-9654-f184760099cf)

**Comment by ym** [comment]
It appears that your device failed to sync the time. Please run the following command in Terminal to restart JetKVM application to see if it works.

```
killall -9 jetkvm; /userdata/jetkvm/bin/jetkvm_app > /userdata/jetkvm/last.log 2>&1 &
```

**Comment by Eric-Schubert** [comment]
You're right, of course.
For me, the issue has been resolved. 
Marking it as solved was maybe a bit hasty on my end.

I can reopen the issue if you need me to.

**Comment by dseven** [comment]
Let's see what @ym wants to do.... but it likely will happen to you again until a proper fix is implemented. We suspect it's caused by the attempt to sync the clock happening before the DNS resolver has been completely configured during boot - depending on timing, it will happen sometimes and not others - called a "race condition".

**Comment by LordSimal** [comment]
I can confirm, that this error happens, if DNS has been cut of for "longer" periods of time.

But the sad part is, that "just" a reboot/disconnection of power doesn't fix it. 

Doing a 
```
killall -9 jetkvm; /userdata/jetkvm/bin/jetkvm_app > /userdata/jetkvm/last.log 2>&1 &
```
indeed fixes the problem (without another reboot after that).

If it helps this is the log file it generated:
```
# cat /userdata/jetkvm/last.log 
2021-01-01T12:21:18Z INF jetkvm jetkvm config loaded path=/userdata/kvm_config.json
2021-01-01T12:21:18Z INF jetkvm jetkvm starting JetKVM app_version=0.4.1 system_version=0.2.4
2021-01-01T12:21:18Z WRN jetkvm watchdog unable to open /dev/watchdog, skipping watchdog reset error="open /dev/watchdog: device or resource busy"
2021-01-01T12:21:19Z INF jetkvm jetkvm loaded Root CA certificates ca_certs_loaded=170
2021-01-01T12:21:19Z INF jetkvm network hostname set fqdn=jetkvm-c224982ffba08176.local hostname=jetkvm-c224982ffba08176
2021-01-01T12:21:19Z ERR jetkvm network failed to get dhcp lease expiry error="uptime or lease time isn't set" interface=eth0
2021-01-01T12:21:19Z INF jetkvm network interface state transitioned to up
2021-01-01T12:21:19Z INF jetkvm network IPv4 address found ipv4=192.168.0.143
2021-01-01T12:21:19Z INF jetkvm network IPv6 link local address found ipv6=fe80::46b7:d0ff:fee2:bcbd
2021-01-01T12:21:19Z INF jetkvm network IPv6 address found ipv6=2001:871:208:425:46b7:d0ff:fee2:bcbd
2021-01-01T12:21:19Z INF jetkvm timesync RTC device found path=/dev/rtc0
2021-01-01T12:21:19Z INF jetkvm timesync read RTC time rtc_time=0001-01-01T00:00:00Z
2021-01-01T12:21:19Z INF jetkvm native server listening socket_path=/var/run/jetkvm_ctrl.sock
2021-01-01T12:21:19Z INF jetkvm timesync syncing system time
2021-01-01T12:21:19Z INF jetkvm native server listening socket_path=/var/run/jetkvm_video.sock
2021-01-01T12:21:19Z INF jetkvm native jetkvm_native binary started pid=314
2021-01-01T12:21:19Z INF jetkvm network hostname set fqdn=jetkvm-c224982ffba08176.pfiff.me hostname=jetkvm-c224982ffba08176
2021-01-01T12:21:19Z INF jetkvm jetkvm mDNS server started ipv4=true ipv6=true local_names=["jetkvm-c224982ffba08176","jetkvm-c224982ffba08176.pfiff.me"]
2021-01-01T12:21:19Z INF jetkvm network udhcpc lease loaded data={"bootp_next_server":"192.168.0.10","broadcast":"192.168.0.255","dns_servers":["192.168.0.10"],"domain":"pfiff.me","ip":"192.168.0.143","lease":86400000000000,"netmask":"255.255.255.0","ntp_servers":["192.168.0.10"],"routers":["192.168.0.1"],"server_id":"192.168.0.10"} interface=eth0 ip=192.168.0.143 leaseTime=24h0m0s
2021-01-01T12:21:19Z INF jetkvm timesync NTP server returned time clockOffset=38612h37m56.882276944s reference=.GPS. rtt=25.098688ms server=1.pool.ntp.org stratum=1
2025-05-29T08:59:16Z ERR jetkvm timesync failed to sync system time error="failed to set system time: failed to get RTC device fd: open /dev/rtc0: device or resource busy"
2021-01-01T12:21:19Z INF jetkvm timesync NTP server returned time clockOffset=38612h37m56.877440668s reference=10.209.8.4 rtt=25.072098ms server=3.pool.ntp.org stratum=3
2021-01-01T12:21:19Z INF jetkvm timesync NTP server returned time clockOffset=38612h37m56.878068105s reference=193.171.23.163 rtt=30.836209ms server=2.pool.ntp.org stratum=2
2025-05-29T08:59:16Z INF jetkvm timesync NTP server returned time clockOffset=38612h37m56.872756188s reference=.GOOG. rtt=63.893381ms server=time.google.com stratum=1
2025-05-29T08:59:16Z INF jetkvm usb usbgadget configuration updated
2025-05-29T08:59:16Z INF jetkvm jetkvm initial virtual media state set initial_virtual_media_state=null
2025-05-29T08:59:16Z INF jetkvm usb USB state changed from=configured to=configured
panic: listen tcp :80: bind: address already in use

goroutine 115 [running]:
github.com/jetkvm/kvm.RunWebServer()
	github.com/jetkvm/kvm/web.go:537 +0x68
created by github.com/jetkvm/kvm.Main in goroutine 1
	github.com/jetkvm/kvm/main.go:113 +0x600
2021-01-01T12:21:18Z WRN jetkvm timesync system time is behind the built time, time sync is needed built_time=2025-05-22T09:23:47Z now=2021-01-01T12:21:18Z
2021-01-01T12:21:18Z WRN jetkvm cloud system time is not synced, will retry in 3 seconds
2021-01-01T12:00:02Z INF jetkvm native RTVersion        12:00:02-887 {dump              :064} ---------------------------------------------------------
RTVersion        12:00:02-887 {dump              :065} rockit version: git-4720dc10a Tue Apr 30 15:47:55 2024 +0800
RTVersion        12:00:02-887 {dump              :066} rockit building: built- 2024-04-30 15:53:43
RTVersion        12:00:02-888 {dump              :067} ---------------------------------------------------------
(null)           12:00:02-888 {read_log_level    :098} text is all=4
(null)           12:00:02-888 {read_log_level    :100} module is all, log_level is 4
 pipe=stderr
2025-05-29T08:59:18Z INF jetkvm display set brightness brightness=64
2025-05-29T08:59:19Z INF jetkvm cloud websocket connected connectionID=9474cb85fa1a5b90-VIE url=wss://api.jetkvm.com
2025-05-29T08:59:19Z INF jetkvm websocket new websocket connection established connectionID=9474cb85fa1a5b90-VIE source=api.jetkvm.com sourceType=cloud
2025-05-29T08:59:21Z WRN pion mdns [0x1ef3350] failed to parse mDNS packet parsing/packing of this type isn't available yet
2025-05-29T08:59:21Z WRN pion mdns [0x1ef3350] failed to parse mDNS packet parsing/packing of this type isn't available yet
2025-05-29T08:59:22Z WRN pion mdns [0x1ef3350] failed to parse mDNS packet parsing/packing of this type isn't available yet
2025-05-29T08:59:22Z WRN pion mdns [0x1ef3350] failed to parse mDNS packet parsing/packing of this type isn't available yet
2025-05-29T08:59:23Z ERR jetkvm native timeout waiting for response action=lv_obj_clear_flag params={"flag":"LV_OBJ_FLAG_HIDDEN","obj":"ui_Home_Header_Cloud_Status_Icon"}
```

**Comment by alexballas** [comment]
These are the timeservers

```
var defaultNTPServers = []string{
	"time.apple.com",
	"time.aws.com",
	"time.windows.com",
	"time.google.com",
	"162.159.200.123",   // time.cloudflare.com IPv4
	"2606:4700:f1::123", // time.cloudflare.com IPv6
	"0.pool.ntp.org",
	"1.pool.ntp.org",
	"2.pool.ntp.org",
	"3.pool.ntp.org",
}
```
Could it be that some of them fail? (maybe the ipv6 one?) I would probably test every one and try to isolate the issue.

**Comment by nackerr** [comment]
I also had this same issue today. Killing the JetKVM service like @ym said fixed it, but for how long?

**Comment by IDisposable** [comment]
Given that it's been potentially diagnosed by @dseven as a race condition caused by DNS not being up yet, perhaps we should do a few things

1. Change the order list of the NTP / HTTP time sources to have the IP (not hostname) listed first so that we can connect out even if DNS is not up yet
2. Add some retry logic to respawn the NTP call-out if we get errors in resolve
3. Make sure we honor the DHCP NTP server if sent

Additionally for those running in your own home-lab, setting up a local NTP server somewhere on your LAN is pretty easy. I used [crony](https://github.com/hassio-addons/addon-chrony) on my Home Assistant box

**Comment by dseven** [comment]
What we observed [on Discord](https://discord.com/channels/1270105230989594634/1375027791950516244) (another user experienced this - not me) was errors like:

```
2021-02-16T06:27:06Z INF jetkvm timesync RTC device found path=/dev/rtc0
2021-02-16T06:27:06Z INF jetkvm timesync read RTC time rtc_time=2021-02-16T06:27:06Z
2021-02-16T06:27:09Z INF jetkvm timesync syncing system time
2021-02-16T06:27:09Z WRN jetkvm timesync failed to query HTTP server error="Get \"http://www.gstatic.com/generate_204\": dial tcp: lookup www.gstatic.com on [::1]:53: read udp [::1]:57871->[::1]:53: read: connection refused" http_url=http://www.gstatic.com/generate_204 status=0
2021-02-16T06:27:09Z WRN jetkvm timesync failed to query HTTP server error="Get \"http://edge-http.microsoft.com/captiveportal/generate_204\": dial tcp: lookup edge-http.microsoft.com on [::1]:53: read udp [::1]:35017->[::1]:53: read: connection refused" http_url=http://edge-http.microsoft.com/captiveportal/generate_204 status=0
2021-02-16T06:27:09Z WRN jetkvm timesync failed to query HTTP server error="Get \"http://cp.cloudflare.com/\": dial tcp: lookup cp.cloudflare.com on [::1]:53: read udp [::1]:42892->[::1]:53: read: connection refused" http_url=http://cp.cloudflare.com/ status=0
```

i.e. it appeared to be trying to use "localhost" for DNS lookups (port 53), even some time after boot, but starting a new instance of the app "fixed" it. @ym hypothesised that it may have been using a cached copy an empty resolv.conf

**Comment by systemmonkey42** [comment]
> Could it be that some of them fail? (maybe the ipv6 one?) I would probably test every one and try to isolate the issue.

Thanks for the TIP.  I moved the JetKVM to a network without IPv6 (no SLAAC from the router) and the problem disappeared immediately.

**Comment by LordSimal** [comment]
> I moved the JetKVM to a network without IPv6

That is not a solution for a software in 2025...
Proper IPv6 support shouldn't be that hard

**Comment by timocov** [comment]
> Does the problem go away if you select NTP only in the Settings/Network/Time synchronization

It doesn't for me.

**Comment by AJolly** [comment]
switching it to ntp only so far is solving it

**Comment by systemmonkey42** [comment]
> switching it to ntp only so far is solving it

That didnt work for me, but I dont think I rebooted when testing it.  

Issue https://github.com/jetkvm/kvm/issues/576 (resolved by https://github.com/jetkvm/kvm/pull/605) indicates that the HTTP time support was the issue.

**Comment by systemmonkey42** [comment]
The fix in the latest update (app 0.4.4) appears to have resolved it for me.
