### ISSUE TITLE
0.4.8 Keyboard Issue - doing keyup when it wasn't released

### ISSUE THREAD

**Issue by dustbrown** [jetkvm/kvm#820]
### Disclaimer

- [x] I have read and understood the disclaimer.

### Application version

0.4.8

### System version

0.2.5

### Device model

JetKVM

### Extension model

None

### Remote device Hardware

MiniPC

### Remote device OS

Windows 11

### Bug description

This didn't happen prior to 0.4.8, just started today. When I am trying to hold down a key, for example right arrow key, about 20% of the time it'll release the key after like 500ms even though I have the key still held down. I can verify this by seeing the "Show Pressed Keys" option.

You can test this by opening notepad with a bunch of text and keep press+holding the right arrow key (or left arrow key) for a few seconds and repeat 5-10 times, and you should see it happen.

Note: before (0.4.6 I think I was on) sometimes if I tapped two keys very close to each other, then sometimes one would be kept held down by JetKVM, this happened ~5% of the time. The double tap issue seems like it was fixed in 0.4.8, however, the new issue introduced in 0.4.8 is much more annoying in general...

**Comment by computergeek125** [comment]
Also present on remote OS Linux Mint.  This showed up for me around the same time that 0.4.8 released.  I didn't do a ton of testing on 0.4.7-dev since my rig wasn't properly online, I don't think I saw it on that dev release, but can't be positive

On my box this behavior is closer to 80-95% of the time for the incorrect key held -> key up behavior.  The behavior is somewhat inconsistent, so I don't know if I've matched up the correct patterns or I just got (un)lucky with what I was looking at.
- Spacebar seems more reliably able to be held down, but not always
- "Standard" keys seem to have some behavior where they're more likely to show the correct held behavior if mouse inputs or chorded mouse keys (i.e. L+R mouse) are being input simultaneously with the keyboard events

Application: 0.4.8  
System: 0.2.5  
Device: JetKVM  
Extension: ATX Power  
Remote device hardware: 
 - ATX tower PC
 - Ryzen Threadripper 2970WX
 - Asrock motherboard
 - Nvidia Quadro P2000 GPU

Remote device software:
 - Linux Mint 22.1 (Xia -- Ubuntu/Noble)
 - `nvidia-driver-580`

**Comment by IDisposable** [comment]
Distinctly possible that we're not sending keep-alive messages fast enough and the device is auto-releasing. I will look

**Comment by tkeifer** [comment]
Pretty sure I am running into this issue as well. (Mac OS X -> JetKVM -> Mac Laptop) My "MetaLeft" (left Cmd key) is auto-released even when held down. This has broken cut & paste functionality with my left hand. (right Cmd still works) Also seemed to have appeared around the 0.4.8 release.

**Comment by adamshiervani** [comment]
Could you please take a screenshot of your "Connection Stats" while this is happening?

**Comment by tkeifer** [comment]
Attached is stats while pressing left Cmd repeatedly. (Note: the large packet spike was after my test keystrokes, possibly unrelated)

<img width="482" height="842" alt="Image" src="https://github.com/user-attachments/assets/c5dbbfb8-f390-43d1-9ef0-d0843f35bd60" />

<img width="482" height="842" alt="Image" src="https://github.com/user-attachments/assets/e57088d5-1a16-45fe-8ff1-cab4be76f8d5" />

**Comment by adamshiervani** [comment]
@tkeifer I found the cause of your problem.

@IDisposable Remember the reason for [this](https://github.com/jetkvm/kvm/blame/74e64f69a7ca2d076bd4ba991e6a36fcbdf5a3d2/ui/src/components/WebRTCVideo.tsx#L267). I commented out those lines, and on my MacOS Tahoe 26, I'm getting the keyup event when I release the physical key.

**Comment by tkeifer** [comment]
@adamshiervani - Amazing! great work. Will be anxiously awaiting a (hopefully easy for you) fix.

**Comment by IDisposable** [comment]
> I commented out those lines

... I suppose git blame says I wrote them, but they were there before I ever started... if that's no longer the case, I'm all for deleting special-case logic... 

Honestly, I was about to put in an option to _disable_ the timer-based forced keyboard release as my next step, because key-repeat is still not working for me :(

**Comment by madmath** [comment]
Thanks, any update on this one?

**Comment by dustbrown** [comment]
@adamshiervani , I just tried to repro this issue today on the latest version (0.5.4 + 0.2.7), and I cannot. It seems like it is fixed to me. I've been using a diff KVM over IP for the last few months so I didn't have much use on JetKVM, but I'll swap this back over to my main PC and try it out for a few weeks...

But I think you can likely close this bug if you cannot repo either, it's either MUCH MUCH better than 0.4.8, or completely fixed.

**Comment by mbassalbioinformatics** [comment]
I have a KVM that was updated to 0.5.5 and this issue is back in the latest build. Very difficult to do any 2 button combinations.  I still have 2 KVM on 0.5.4 and this issue isnt on those builds. So its something specific to 0.5.5. (Possibly related to the expanded/stretched view window?? Just guessing...)
