### ISSUE TITLE
Stuck at "Loading video stream..."

### ISSUE THREAD

**Issue by ChrisDowning** [jetkvm/kvm#84]
Just got my JetKVM - setup went fine, initial connection to my first machine (which already has an OS installed) worked OK. After uploading some ISOs to use as boot media for other machines, I noticed the video stream had stopped working. Unplugging and rebooting the JetKVM made no difference.

I moved on to trying the device with a new machine with no OS yet installed, but was not able to get any response - the console shows USB connected, but the screen viewer just seems stuck at "Loading video stream...". Rebooting both the JetKVM and the target device had no effect.

Switching to a third machine, I saw exactly the same behaviour as the second - i.e. no video display output is ever shown, just "Loading video stream...".

I have also tried enabling the developer stream updates (and rebooting the device) as well as changing the stream quality - all with no effect.

On the third machine (which apparently has Windows pre-installed and a built-in speaker!) I can hear familiar connected/disconnected chimes when I change the EDID - but none of the settings result in a working video output.

**Comment by freddyouellette** [comment]
I'm in a similar situation, when accessing the JetKVM from a remote location through `app.jetkvm.com`, I can login successfully but I only see "Loading video stream...". Once it times out, it will show the "Connection Issue Detected" screen, then a couple seconds later it will try to load again and repeat.

![Image](https://github.com/user-attachments/assets/c817234d-7305-416c-a71f-1f5ddc961a1a)

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/5132b18b-81c2-4bef-b1ea-c488bb3ce834" />

When connecting through the local network directly on the IP given by the device, it works. The video loads and the HDMI/USB show no issues. So this problem for me only happens when accessing remotely through JetKVM cloud. I have tried forwarding the IP to my machine remotely with `sshuttle` or `ssh -L` but it does not work, I'm guessing because of limitations to WebRTC.

**Comment by ChrisDowning** [comment]
In my case, the issue occurs even though all devices are on the same LAN (I have not configured the JetKVM cloud setup yet).

Through a bit more testing I have confirmed that the issue is present across both Firefox and Chrome browsers on a MacOS client, Firefox from an Android phone, and both Firefox and Safari on iOS - so can be reasonably confident that this isn't a browser/client issue.

**Comment by ChrisDowning** [comment]
Further problems: when trying to factory reset the device following [these](https://jetkvm.com/docs/advanced-usage/factory-reset) instructions, the following happens:
- Hold button in on an unpowered device
- Plug device in with button held, does not power on
- Hold for 3 seconds as instructed, then release - device still does not power on
- Unplug and replug device, powers on as normal (no factory reset occurs)

**Comment by ChrisDowning** [comment]
Have now completed a full factory reset with new firmware flashing - no effect, still shows "Loading video stream..." forever when connected to a device.

Inspecting the browser console shows: `Attempting to connect WebRTC`.

**Comment by grayblack** [comment]
I suspect it may be an issue when the device is behind a CG NAT

**Comment by Nevexo** [comment]
> I suspect it may be an issue when the device is behind a CG NAT

That's why it uses STUN/TURN, to avoid NAT issues. This isn't a NAT issue it's something else, annoyingly.

**Comment by grayblack** [comment]
If you are behind a CGNAT using STUN to find the real IP is just going to find the un-natted address which is useless. Or am I missing the point?

**Comment by Nevexo** [comment]
> If you are behind a CGNAT using STUN to find the real IP is just going to find the un-natted address which is useless. Or am I missing the point?

Doesn't really matter, sure you'll hit the address of the CGNAT box, but that will forward the traffic back down to the next layer of NAT.

But even if that doesn't work, that's what TURN is for, it forwards the traffic via Cloudflare to avoid the mess that is NAT in the first place.

**Comment by grayblack** [comment]
According to APNIC (responsible for assignment of IPs to Asia Pacific)

> The problem here is that STUN doesn’t work the way we’d like. We’d like to find our ip:port on the ‘middle network’, because it’s effectively playing the role of a miniature Internet to our two peers. But STUN tells us what our ip:port is from the STUN server’s point of view, and the STUN server is out on the Internet, beyond the CGNAT.

https://blog.apnic.net/2022/05/03/how-nat-traversal-works-concerning-cgnats/

Is this right in this case?

**Comment by ChrisDowning** [comment]
> I suspect it may be an issue when the device is behind a CG NAT

The issue I am describing here is not related to CGNAT; all devices are on a LAN with no VPN in the picture. I have disabled Tailscale on my client machine just to double-check, and do not have it configured on the JetKVM.

**Comment by grayblack** [comment]
Ahh yeah you're right! Apologies. Maybe a toasted unit?

**Comment by mqt0029** [comment]
Bit of a long shot, but if you are using Brave (and perhaps followed PrivacyGuides), you might have set WebRTC IP Handling Policy to "Disable non-proxied UDP" like I did, simply changing it back to "Default" fixes the issue for me.

Otherwise, stock Firefox seems to work as well (tested on fresh Ubuntu 24.04 installation).

Setting is located under Privacy and Security (see screenshot).

<img width="733" alt="Image" src="https://github.com/user-attachments/assets/44e555eb-1d3c-4fe1-a875-01dc6471af1a" />

**Comment by RobIrizarry** [comment]
If you're using a VPN, make sure you either disable it or add the JetKVM's IP address as an exception.

**Comment by ChrisDowning** [comment]
I'm not using Brave, and checked the equivalent setting in Firefox (`media.peerconnection.enabled`) - setting this to `false` disrupts the JetKVM connectivity completely, but even with it set back to the original value of `true` I still get the "Loading video stream..." pinwheel indefinitely.

**Comment by boombatower** [comment]
I'm seeing the same loading forever. I've tried the above, updated to latest, played around with all sort of setting on OS, browser, network.

Using firefox `about:webrtc` logs I see `nr_socket_multi_tcp.c:639 function nr_socket_multi_tcp_listen failed with error 3`. Which seems to imply the functionality does not work on LAN: https://bugzilla.mozilla.org/show_bug.cgi?id=1659672.

I use `192.168.7.0` subnet. Pure guess, there is a check for "private IP" indicating LAN that disables the ICE/STUN stuff, but it doesn't check full range of private IPs. This may explain #71 as well.

I'll try testing the theory when I get time, but maybe someone can figure it out before then.

**Comment by ChrisDowning** [comment]
Thanks for the tip about `about:webrtc` - in the logs whenever I have a tab open to connect to the JetKVM I see the same error plus a bunch of other messages, with the following generated seemingly indefinitely:
```
STUN-CLIENT(consent): Received response; processing

ICE(PC:{085bfd92-a583-4554-8b6d-5423386c0f9c} 1738190937542035 (id=526133493761 url=http://192.168.178.169/))/STREAM(PC:{085bfd92-a583-4554-8b6d-5423386c0f9c} 1738190937542035 (id=526133493761 url=http://192.168.178.169/) transport-id=transport_0 - 36758d57:995a7fa16fc3d66d1437ab250feb9256)/COMP(1): Consent refreshed
```

Again, this is with Tailscale installed but disabled on the client and not installed at all on the JetKVM device.

As you can see from the error message, I use a `192.168.178.0` on the LAN, which fits with what @boombatower observed.

**Comment by boombatower** [comment]
In chrome `chrome://webrtc-internals/`:

Seems to imply it's working, but infinite connect

![Image](https://github.com/user-attachments/assets/de6518f6-a19b-4a37-a439-6ac248110ca9)

**Comment by ChrisDowning** [comment]
Tried with Edge rather than Firefox/Chrome/Safari, and while I still see an infinite "Loading video stream..." in the main window, it did cause me to notice 1 difference - on Firefox, all panes of the Connection Status sidebar show "Waiting for data..." and do not produce graphs. On all other browsers, the "Packets Lost" and "Round Trip Time" graphs do show up - I see a flat line of 0 packets lost, and an RTT from 3 to 50 ms.

**Comment by badokami** [comment]
Stopped by to report that I too am suffering the "Waiting for video..." problem. Only difference appears to be that all my systems are Windows 11. Firefox/Edge connect to the KVM when I'm internal to my local network but accessing the KVM via the Internet (registered) just loops the waiting for video... with the "Connection Issue" page popping up and disappearing so quickly, it's almost impossible to click it.

I hope this is a firmware fix and not a bad unit!

**Comment by TheGurT** [comment]
I have the exact same issues, so I will be following this page to the letter.

**Comment by ryangreen19** [comment]
Same issue here, stuck at video stream loading even though the device is online. Can connect through devices while on the same local network, but not over internet. Neither brave or Firefox or chrome have worked on my iPhone.

**Comment by oguzoezgen** [comment]
Same issue here. However, i sit behind a CGNAT / LTE Router.

**Comment by grayblack** [comment]
> Same issue here. However, i sit behind a CGNAT / LTE Router.

Works fine for me after using the fix suggested in another thread. Also behind CGNAT. You need to add an alias for your wan IP on the eth0 interface. It's a bug and they will fix it eventually.

**Comment by oguzoezgen** [comment]
> > Same issue here. However, i sit behind a CGNAT / LTE Router.
> 
> Works fine for me after using the fix suggested in another thread. Also behind CGNAT. You need to add an alias for your wan IP on the eth0 interface. It's a bug and they will fix it eventually.

Can you direct me to which solution worked?
I now tried this: 
ifconfig eth0:0 $(/usr/bin/wget http://api.ipquery.io/ -O- -q)

Even I finally get a public IP adress, still can´t connect from non-local network.

**Comment by W7MN** [comment]
I'm having the same video loading issue while using my 2017 MacbookPro.  Safari, Firefix, etc... Accidentally found a work around when typing in the IP address I could see in my history   http://192.168.X.XX/welcome/mode    By going to that page it gave me an option to use a password (I had not originally) and by clicking 'no' again, it loaded the video.  24 hrs later I was back to the video stream not loading, but a return to the welcome mode page allows me in again.  Only having this issue with my MacbookPro, and not my other machines.  I'm sure its being worked on and appreciate that greatly.  Just wanted to add my discovery.

**Comment by grayblack** [comment]
Have you tried the fix:
https://github.com/jetkvm/kvm/issues/54#issuecomment-2628461587

Issue #54 has more context on the temporary fix, as well as how to make it automatic at boot.

**Comment by ChrisDowning** [comment]
I've now tried both of the new suggestions mentioned here (`ifconfig eth0:0 $(/usr/bin/wget http://api.ipquery.io/ -O- -q)` on the JetKVM device via SSH, and resetting the password auth via http://192.168.x.xx/welcome/mode) - neither of these had any impact.

**Comment by oguzormanci** [comment]
Would have been nice to get some responses from JetKVM on this thread at least. I have 5 JetKVMs and they are all sitting idle, when I needed them the most...

**Comment by Nevexo** [comment]
> Would have been nice to get some responses from JetKVM on this thread at least. I have 5 JetKVMs and they are all sitting idle, when I needed them the most...

https://github.com/jetkvm/kvm/pull/146 The fix literally just got pulled in. It should be available in the next dev channel release once the cloud API is upgraded.

**Comment by boombatower** [comment]
Hmm, seems to have no affect.

**Comment by ym** [comment]
Hi @boombatower,

Could you please check if WebRTC is enabled in your browser and confirm that Chrome can communicate over the LAN IP address? Enabling WebRTC often resolves issues related to local network communications.

If WebRTC is already enabled, but you’re still encountering problems, would you mind providing some logs from the device for further analysis? Here’s how:

1. SSH into the device and edit `/oem/usr/bin/RkLunch.sh`.
2. Locate the line:
```bash
/userdata/jetkvm/bin/jetkvm_app > /userdata/jetkvm/last.log 2>&1 &
```

and prepend `PION_LOG_TRACE=all` so it becomes:

```bash
PION_LOG_TRACE=all /userdata/jetkvm/bin/jetkvm_app > /userdata/jetkvm/last.log 2>&1 &
```

3. Reboot the device, so the changes can take effect.
4. Download the log by running this command on your local machine:

```bash
ssh root@YOUR_DEVICE_IP "cat /userdata/jetkvm/last.log" > jetkvm.log
```

Once you have the jetkvm.log file, please send to `siyuan+jkk-issue84#buildjet.com`. Free feel to encrypt it as it might contain sensitive information. My PGP key can be found here: [452E12AC4EAE59B6641C6595924A7AC00F5F21E5](https://keys.openpgp.org/vks/v1/by-fingerprint/452E12AC4EAE59B6641C6595924A7AC00F5F21E5)

After collecting the logs, don't forget to remove the `PION_LOG_TRACE=all` setting, as it generates a large volume of logs and might shorten the lifespan of the device's built-in storage.

**Comment by boombatower** [comment]
I'll work on providing the request information, but webrtc is enabled (see above comments from me and others).

**Comment by boombatower** [comment]
This was with Firefox, but I've tried others and different settings.

[jetkvm.log](https://github.com/user-attachments/files/18762174/jetkvm.log)

**Comment by badokami** [comment]
Can confirm APP: 0.3.5-dev202502111730 & System 0.2.0 have fix the "Video loading..." for me. I successfully made my first remote change to the BIOS of a target machine and rebooted it.

**Comment by adamshiervani** [comment]
We’ve deployed a fix to the Dev Channel. If no issues arise, we’ll proceed with a main channel release.

Keep in mind that both the local and remote access runs on WebRTC. If your browser or VPN blocks WebRTC, our fix won’t resolve your issue.

If you're still having issues, and are certain that WebRTC is allowed (you can test [here](https://webcasts.com/webrtc/)), please follow the instructions @ym [here](https://github.com/jetkvm/kvm/issues/84#issuecomment-2651605998).

For those, daring enough to test the dev channel, please report back if the fix solves your issue. Thanks!

**Comment by boombatower** [comment]
Seems like we're mixing local and remote access between these issues. I verified a local connection still doesn't work locally `0.3.5-dev202502121523`. I can connect to web interface, update it, change settings, but video never starts.

I sent log to @ym.

**Comment by adamshiervani** [comment]
Agreed. There seem to be three issues related to the *“Loading Video Stream...”* problem:

1. **STUN/TURN can't be accessed** – This should be fixed in the dev release.  
2. **Computer/Browser blocks WebRTC** – The fix is to whitelist JetKVM or enable WebRTC.  
3. **Peer connection to your device is established, but no video stream** – This appears to be your case, @boombatower, as confirmed in your `chrome://webrtc-internals` screenshot and if the connection wasn’t set up, you wouldn’t be able to  
     [access the settings](https://github.com/jetkvm/kvm/blob/63b3ef015188501ffcc3d9f63a5376d07b018c6a/ui/src/components/WebRTCVideo.tsx#L415-L423).  

While @ym reviews your logs, could you check one thing for me?  

Go to **Settings > Advanced > Enable Troubleshooting Mode**.  
At the bottom of the UI, you should see some metadata. Could you post that here?

**Comment by ChrisDowning** [comment]
I have upgraded to `0.3.5-dev202502121523` but unfortunately still see the problem. WebRTC tests all appear to be fine.

Here is a screenshot of what I see, with the troubleshooting metadata enabled. 

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/e420c976-9c5f-4300-8926-7789eb68759e" />

@ym : Prior to the most recent software update I performed the steps you provided and have emailed a log file to you.

**Comment by lordpengwin** [comment]
I have this problem with Chrome but not with Safari.

**Comment by Nevexo** [comment]
> I have this problem with Chrome but not with Safari.

Do you have private relay enabled?

**Comment by lordpengwin** [comment]
Where is private relay set?

**Comment by Nevexo** [comment]
> Where is private relay set?

It'll be under your iCloud account in Preferences. You'll only have it if you pay for iCloud.

**Comment by lordpengwin** [comment]
No, I don't have that set.

**Comment by dannyducko** [comment]
Can confirm the dev update channel fixed my issue also. Could not access JetKVM remotely due to video not loading/ spinning wheel. Thanks!

**Comment by ChrisDowning** [comment]
Checking in - I am still seeing this issue across all browsers, still using a local (non-cloud) connection.

I have identified at least 2 other issues (web terminal not working in Firefox, and unable to change EDID when connected to a certain device) - but the core issue of not being able to get a video stream remains the same.

**Comment by Nevexo** [comment]
> Checking in - I am still seeing this issue across all browsers, still using a local (non-cloud) connection.
> 
> I have identified at least 2 other issues (web terminal not working in Firefox, and unable to change EDID when connected to a certain device) - but the core issue of not being able to get a video stream remains the same.

Have you upgraded to 0.3.7?

**Comment by ChrisDowning** [comment]
Yes - versions are:
App: 0.3.7
System: 0.2.2

**Comment by boombatower** [comment]
After activating cloud mode I am able to connect both remotely over internet (phone connection) and locally directly via 192.168...

I disabled it wondering if it being active made any difference and even rebooted the jetkvm, but it still works now. 🤷

**Comment by TonyHoyle** [comment]
Same symptoms here.  Stuck loading video stream, 'connecting', everything greyed out.  I tried a DFU restore and it didn't change anything.  Is there a way to DFU the dev update or am I hosed until the fix is released?

**Comment by trickiegt** [comment]
I hope this helps some of you.. I use Vivaldi and had the same issue with loading the video stream.  It is working now after I made some changes.  I will share some things I noticed and then at the bottom the change I needed.
Noticed - WebRTC IP Broadcast setting -- If disabled, I could not see the status of device /usb status -- enabled it would show that data

I loaded the dev-tools and went to console.  There I noticed something about WebGL not working or being supported or something... So I looked that up and followed the instructions from this webpage - https://forum.vivaldi.net/topic/60277/how-to-enable-hardware-acceleration-webgl-in-vivaldi-on-pi4/3

After it restarted the browser, I have the video stream -- Haven't tested actually using it yet lol

![Image](https://github.com/user-attachments/assets/f5709973-96a4-46fb-add7-224ed8f46c20)

![Image](https://github.com/user-attachments/assets/d3dcc088-06b5-4717-9655-08d0878ba30c)

**Comment by nomadmd1** [comment]
On MS Edge one more thing can lead to "Loading video stream..." issue. For me this was Autoplay setting set to "Block". To fix it go to edge://settings/content/mediaAutoplay and add the URL for your JetKVM to "Allow" list.

**Comment by dbent** [comment]
I had this occur specifically with LibreWolf, allowing autoplay fixed it for me.

**Comment by Andreag00** [comment]
Hello everyone, 
Just here to report that I've been having issues as well.

I was able to get it working immediately on Safari on my iPhone BUT I can't get it to work on my PC. I've tried both Firefox and Ungoogled Chromium on Fedora Silverblue 41 and it seems that either of them can establish a WebRTC connection with the JetKVM. For example, Firefox console shows this:

![Image](https://github.com/user-attachments/assets/0909b8f4-a9c6-4b0b-9a4d-8703dddbe0f8)

Seems like the JetKVM is sending malformed SDP packets. Firefox's `about:webrtc` logs show this:

```
ICE(PC:{bb36f859-65cf-4f36-b26c-0e8025e5ed23} 1742641918758269 (id=60129542147 url=http://10.0.1.214/)): All candidates initialized

/builddir/build/BUILD/firefox-136.0-build/firefox-136.0/dom/media/webrtc/transport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:639 function nr_socket_multi_tcp_listen failed with error 3

ICE-STREAM(PC:{1fc9694f-1b47-4315-8639-581d35d61875} 1742641921765908 (id=60129542147 url=http://10.0.1.214/) transport-id=transport_0 - 6d4889f6:08d849ed793847962e0635cd310c7dc9): failed to create passive TCP host candidate: 3
```

Because of this even if I try connecting locally this is what I get:

![Image](https://github.com/user-attachments/assets/c38c7a60-0df3-41ea-8482-e9079d446107)

I have also tried enabling remote access and trying to connect via JetKVM's cloud service but that does not work either and does not work on Safari either but that may very well be my firewall I guess.

Any other troubleshooting steps I can help with to figure this out?

Andrea

**Comment by phatlewt** [comment]
I had this issue also but then realized the default setting in my browser was not to autoplay videos. Set it to autoplay video/audio for the kvm site and the video stream automatically starts after reloading the page. Not sure if it's the same issue as what others are facing but might be worth a try.

![Image](https://github.com/user-attachments/assets/217f4839-e2d6-4b41-b716-940ddec8a299)

**Comment by mlavi** [comment]
> Set it to autoplay video/audio for the kvm site and the video stream automatically starts after reloading the page.

Thank you, this was my issue!
I recently switched browsers and I'm getting used to the default security settings, so this didn't register for troubleshooting.

**Comment by fervagar** [comment]
Hello,

Same here. I tested this on GNU/Linux (Debian), and JetKVM failed to connect using any browser I tried—Firefox, Chrome, Chromium, and Brave. WebRTC is confirmed enabled.

Connection attempts via both LAN IP and cloud access were unsuccessful.

Ultimately, I was only able to connect using a Windows 11 VM with Edge.

**Comment by fervagar** [comment]
For me, autoplay did not solve anything

**Comment by adamfeldman** [comment]
> [I use Vivaldi and had the same issue with loading the video stream.](https://github.com/jetkvm/kvm/issues/84#issuecomment-2726791485)

I also use Vivaldi (on macOS) and the tips above did not work for me.

**Comment by alexhk** [comment]
On Chromium (ungoogled) I was first stuck on "Loading video stream...". 

After clicking on 'Not secure' left of the address bar I enabled WebRTC and now all is good.

![Image](https://github.com/user-attachments/assets/fb884bfb-a404-4ba2-b7cd-661acf1d6237)

**Comment by adamfeldman** [comment]
> > [I use Vivaldi and had the same issue with loading the video stream.](https://github.com/jetkvm/kvm/issues/84#issuecomment-2726791485)
> 
> I also use Vivaldi (on macOS) and the tips above did not work for me.

I fixed my issue in Vivaldi, presumably this affects other Chrome-based browsers as well. I had to enable a privacy-sensitive setting related to WebRTC.

![Image](https://github.com/user-attachments/assets/238e79ce-bf00-4e46-b43d-6d83d8ce425e)

**Comment by gizzieballs** [comment]
I am having the same issue, only after updating the software. Previously it would skip in and out and I could see it booting, and today, it is taking a solid 10 minutes to see anything after a restart, if ever.

**Comment by TonyHoyle** [comment]
Tried the just announced version as it mentioned a firefox fix but exactly the same error.  Pretty much the same #issuecomment-2745235593 - some kind of syntax error on the page.

**Comment by manic101** [comment]
I'm having the same issue stuck at "video stream loading..." in Edge browser. 
Work fine when i use In-Private Browsing.

**Comment by derbo904** [comment]
I'm having this issue with all my Macs with firefox, chrome and safari. I believe this all started after the update with the new mouse setup.

**Comment by przemo-c** [comment]
Tried firefox, clean brave install, chromium, firefox for android, edge. Tried all the options mentioned above and I still get Loading video stream. Still can't change EDID (Failed to set EDID: timeout waiting for response) with troubleshooting on the status bar indicates:

`Resolution:0x0 Video Size:300x150 Pointer: 0,0 USB State: configured HDMI State: ready Keys:`

Tried restarting it clearing settings and updating App: 0.3.8 System 0.2.3 Nothing helps.

**Comment by ChrisDowning** [comment]
Still the same issue for me across Firefox, Chrome and Safari on MacOS, Edge on Windows, and Firefox on Android. Also running the latest versions (App 0.3.8 / System 0.2.3). I also tried reconfiguring my home network from `192.168.178.0/24` to `192.168.0.0/24` based on some of the suspicions raised earlier in the thread, but that didn't help.

**Comment by vhristev** [comment]
I can also confirm same `Loading video stream` issue with:
MacOSX: Sequoia  15.3.2 (24D81)
Tried with: 

- Safari
- Chrome
- Firefox

**Comment by Pingger** [comment]
With the 0.3.8 version I now also can't use my work around of using Brave Browser. That is now also stuck in loading ... but it gets further than firefox, as in brave I can at least access the extension board to "press" the power button for starting / hard resetting...
Just for reference I am using a 192.168.1.0/24 network, which is behind a double NAT. And with version 0.3.7 at least Brave browser worked.

**Comment by kmanwar89** [comment]
Strangely enough...I tried connecting this morning and it seemed to work, at least for the JetKVM connected to my Pi 5. I initially had the "loading video stream" screen, switched tabs over to GitHub (to monitor updates from this issue), switched back and the video stream had loaded.

Identical setup as before (Brave on an M3 Mac running MacOS Sequoia 15.3.2 (24D81)). Only difference is I'm remotely connecting to my home network via Tailscale, but I'm still accessing the JetKVM through app.jetkvm.com.

TL;DR - issue is still present. Interestingly, I see the following in the Developer Tools of Brave, which appears to confirm the WebRTC-related behavior as previously noted.

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/7832842d-9b82-4352-b841-56dca542f5fc" />

**Comment by soldierj** [comment]
First is that I set up the device on a separate system and works flawlessly. Now on my home box I have replaced the USB cables to the computer. Tried two different video cards, HDMI to DP adaptor, tried all the usb plugs on this computer and new cat6 cable to the JetKVM. All it will do is cycle from connected to disconnected every couple of seconds, never stopping.

![Image](https://github.com/user-attachments/assets/ed9de666-b318-455b-9e0d-936157232738)

Any ideas?
Tried Chrome, Edge and Brave

**Comment by JonoYang** [comment]
I encountered this issue on Firefox 128.8.0esr on Debian testing and I was able to resolve it by enabling the "OpenH264 Video Codec provided by Cisco Systems, Inc." plugin in the add-ons manager

**Comment by marktay** [comment]
Connecting to a bare metal Ubuntu machine - works once then wont connect and also brings down RDP and requires a hard reboot of the Ubuntu machine, happens both on the web client and cloud client. KVM connected via Ugreen Displayport to mini HDMI cable, Chrome Browser on W11 (although I dont think its this),

**Comment by wikid24** [comment]
can confirm same issue in Firefox 137.0.1 (64-bit) on Windows 10, solution for me was to enable WebRTC peer connections

in firefox go to "about:config" and search "media.peerconnection.enable" and make sure that it is set to "true"

I had it purposely set to false for security hardening but hey at least the solution works

**Comment by adamshiervani** [comment]
Hey,

We just released version [0.3.9](https://github.com/jetkvm/kvm/releases/tag/release%2F0.3.9), which should handle most known connection issues. The update is rolling out now, but it may take a few days to reach all devices.

If you're still running into problems after updating to 0.3.9, start with the [Troubleshooting Guide](https://jetkvm.com/docs/getting-started/troubleshooting).

If that doesn't solve it, we’ll need logs. Send them to `siyuan+jkk-issue84#buildjet.com` and if you want to encrypt it, use the PGP key: [452E12AC4EAE59B6641C6595924A7AC00F5F21E5](https://keys.openpgp.org/vks/v1/by-fingerprint/452E12AC4EAE59B6641C6595924A7AC00F5F21E5).

Here is how you get logs:
<details>
<summary><strong>Troubleshooting Mode (Required)</strong></summary>

Go to **Settings > Advanced** and enable Troubleshooting Mode.  
Close the modal and write down the values shown in the status bar at the bottom of the page.

</details>

<details>
<summary><strong>Browser Console Logs (Required)</strong></summary>

1. Right-click anywhere on the page and choose **Inspect**.
2. Open the **Console** tab, then refresh the JetKVM page and wait for the failure.
3. Select and copy all the logs in the Console, then save them in a text file.
</details>

<details>
<summary><strong>WebRTC Logs (Optional)</strong></summary>

Chrome-based browsers only.  

1. Visit `chrome://webrtc-internals`, then open a new tab with your device’s IP and let it fail.
2. Go back to the WebRTC Internals tab and click **Create a WebRTC-Internals dump**, then download the file.

</details>

<details>
<summary><strong>Device Logs (Optional)</strong></summary>

1. Enable Developer Mode and paste your public key in **Settings > Advanced**.  
2. SSH into the device and edit `/oem/usr/bin/RkLunch.sh`.  
3. Change this line:

    ```bash
    /userdata/jetkvm/bin/jetkvm_app > /userdata/jetkvm/last.log 2>&1 &
    ```

    to:

    ```bash
    PION_LOG_TRACE=all /userdata/jetkvm/bin/jetkvm_app > /userdata/jetkvm/last.log 2>&1 &
    ```

4. Reboot the device.  
5. Pull the log:

    ```bash
    ssh root@YOUR_DEVICE_IP "cat /userdata/jetkvm/last.log" > jetkvm.log
    ```
**Important:** After you collect the log, remove the `PION_LOG_TRACE=all`. It creates large logs and may reduce the device's storage lifespan.

</details>

**Comment by TonyHoyle** [comment]
Troubleshooting mode enabled via mobile (settings greyed out on desktop).  Status bar just says 'keys:'.

Log attached, nothing obvious (this is a change from an earlier version where it was failing to load with a syntax error).

[log.txt](https://github.com/user-attachments/files/19689483/log.txt)

Screen just says 'ICE Gathering completeted'

[log.txt](https://github.com/user-attachments/files/19689693/log.txt)

**Comment by SonOfMercury** [comment]
Im getting the same issue trying to connect to my home KVM and its sort of stuck at "ICE gathering completed" 
just showing the circle going round and round. I could not enable Settings as it is greyed out. Any way to get the logs?

**Comment by SonOfMercury** [comment]
Heres a more longer report when I let it run for a few hours.
I can access the KVM locally via the IP but when using the web (outside the local network) it does not connect.
This started when the JetKVM was updated, this worked flawlessly before.

[JetKvm_Report.txt](https://github.com/user-attachments/files/19781281/JetKvm_Report.txt)

**Comment by ChrisDowning** [comment]
I still face the same issue with the latest software - have gathered all suggested debugging data and sent to the requested address. For now I am focusing only on using Chrome since that seems to be what most people have had success with, but happy to repeat with Firefox or Safari.

**Comment by dleviminzi** [comment]
> Troubleshooting mode enabled via mobile (settings greyed out on desktop). Status bar just says 'keys:'.
> 
> Log attached, nothing obvious (this is a change from an earlier version where it was failing to load with a syntax error).
> 
> [log.txt](https://github.com/user-attachments/files/19689698/log.txt)
> 
> Screen just says 'ICE Gathering completeted'
> 
> ![Image](https://github.com/user-attachments/assets/c959e8d0-9d6c-43b1-80de-51ac46a9c428)

I had this issue. Cleared cookies and things are working correctly now.

**Comment by tuxtof** [comment]
Hello,

I am experiencing the same issue on my end. I have four JetKVM devices, and one of them is displaying the "Loading Video Stream" message.

I tested all of them under the same conditions:

- Local network
- The same cables (USB, HDMI, and network)
- I just switched between the different JetKVM devices.

However, the problem persists with one of them.

I followed the troubleshooting guide, reset the firmware, and upgraded to App version 0.3.9 and System version 0.2.3, but the issue remains the same.

thanks for your help

**Comment by SonOfMercury** [comment]
I think i found a quick workaround but not really a fix, i think JetKVM devs needs to address this for a real fix..
When you see the screen showing "ICE gathering completed" for a while, click on refresh page once and wait for it to cycle thru. It should be able to show the stream. If this doesn't work the first time try hitting refresh again.

**Comment by Andreag00** [comment]
Sooo today I upgraded my PC to Fedora Silverblue 42 and, while I was at it, I ended up removing the official Fedora version of Firefox and I installed the Flatpak from Flathub (because of codec support)

Now everything works fine. No idea if this is related to the upgrade to Fedora 42 (unlikely) or to the move to the Flatpak. 

Just wanted to let everyone know that using the Flatpak version of Firefox might fix the issue and might be worth investigating for the devs

**Comment by thieleke** [comment]
I am unable to get any video on any browser/OS and only see `Loading Video Stream...`

* App: 0.3.9 
* System: 0.2.3
* Standard LAN network setup - no issues with connecting to the device using either the browser or SSH
* Tested with:
    * macOS 15.4.1: Firefox 137.0.2, Chrome 136.0.7103.48, Safari 18.4  
    * Windows 10: Firefox 137.0.2, Edge 135.0.3179.98
    * Android: Firefox
* `dmesg` output:
```
[  174.950614] stream_cif_mipi_id0: open video, entity use_countt 993
[  174.950677] rkcif-mipi-lvds: rkcif_s_fmt_vid_cap_mplane queue busy
[  175.050978] stream_cif_mipi_id0: open video, entity use_countt 994
[  175.051042] rkcif-mipi-lvds: rkcif_s_fmt_vid_cap_mplane queue busy
[  175.151350] stream_cif_mipi_id0: open video, entity use_countt 995
[  175.151416] rkcif-mipi-lvds: rkcif_s_fmt_vid_cap_mplane queue busy
[  175.251746] stream_cif_mipi_id0: open video, entity use_countt 996
[  175.251807] rkcif-mipi-lvds: rkcif_s_fmt_vid_cap_mplane queue busy
[  175.352089] stream_cif_mipi_id0: open video, entity use_countt 997
[  175.352148] rkcif-mipi-lvds: rkcif_s_fmt_vid_cap_mplane queue busy
[  175.452446] stream_cif_mipi_id0: open video, entity use_countt 998
[  175.452515] rkcif-mipi-lvds: rkcif_s_fmt_vid_cap_mplane queue busy
```

Firefox console log:
```
[Websocket] onClose 
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
index-Dw2u_ZN0.js:646:142549
[Websocket] shouldReconnect 
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
index-Dw2u_ZN0.js:646:142487
[Websocket] onOpen index-Dw2u_ZN0.js:646:142648
[Websocket] Received device-metadata message index-Dw2u_ZN0.js:646:142825
[Websocket] Device version 0.3.9 index-Dw2u_ZN0.js:646:142885
[Websocket] Device is using new signaling index-Dw2u_ZN0.js:646:142934
[setupPeerConnection] Setting up peer connection index-Dw2u_ZN0.js:646:144379
[setupPeerConnection] Creating peer connection index-Dw2u_ZN0.js:646:144489
[setupPeerConnection] Peer connection created 
RTCPeerConnection { localDescription: null, currentLocalDescription: null, pendingLocalDescription: null, remoteDescription: null, currentRemoteDescription: null, pendingRemoteDescription: null, signalingState: "stable", canTrickleIceCandidates: null, iceGatheringState: "new", iceConnectionState: "new" }
index-Dw2u_ZN0.js:646:144712
[setupPeerConnection] Creating offer index-Dw2u_ZN0.js:646:145109
ICE Gathering Started index-Dw2u_ZN0.js:646:145838
ICE Gathering completed index-Dw2u_ZN0.js:646:145715
[Websocket] Received answer index-Dw2u_ZN0.js:646:143140
[Websocket] Setting remote answer pending true index-Dw2u_ZN0.js:646:143336
Updating video stream from mediaStream index-Dw2u_ZN0.js:295:49802
[setRemoteSessionDescription] Remote description set successfully index-Dw2u_ZN0.js:646:141334
[Websocket] Received new-ice-candidate index-Dw2u_ZN0.js:646:143531
[setupPeerConnection] Connection state changed connecting index-Dw2u_ZN0.js:646:144968
[setupPeerConnection] Connection state changed connected index-Dw2u_ZN0.js:646:144968
[setRemoteSessionDescription] Remote description set index-Dw2u_ZN0.js:646:141658
```

about:webrtc output: 

[aboutWebrtc.txt](https://github.com/user-attachments/files/19931107/aboutWebrtc.txt)

**Comment by marktay** [comment]
Putting my tin helmet on for this comment, but if the host has a screen save function then you need to open up the virtual keyboard and send a cr to wake it up. Then you get the login

**Comment by BenPi-Ross** [comment]
I first tested my JetKVM from a machine on the same network (same subnet on the the same switch/VLAN) and it was working fine.

But I got the same problem when I moved it to another subnet/VLAN. So I'm accessing it from a computer in a different subnet/VLAN, going through a PFSense firewall to the JetKVM on another subnet/VLAN. (Exemple : Computer [192.168.1.100] -> Firewall -> JetKVM [192.168.2.50])

To fix the issue I created a rule in the firewall to allow TCP/UDP ports 80, (443, for future use) and 49152:65535 (dynamic port range) from my computer IP to the JetKVM IP. I suppose I could narrow the dynamic port range, but I don't know what port range the JetKVM is using.

Hope it helps a few people here!

**Comment by chris-in-texas** [comment]
Not sure if this issue can go here, but I am running the current release of the software, just received my unit.  Running on a WIndows 10 machine with native HDMI output.  When I first turn on the machine connected to the KVM, I can get into the setup screen without any issues everything shows connected on the JetKVM.  I can use the mouse and keyboard just fine as well in the BIOS.  However when W10 starts to load as soon as it goes to the "desktop" the KVM will show "Disconnected" on its display.  I have tried all four monitor options and none of them work.  Not sure what is going on here.  I am no the same network plugged into the same switch.  Windows 10 seems to be doing something as it starts to load, just wondering if anyone else had these issues?

Thanks,Chris

**Comment by rtw819** [comment]
Mine was stuck at the "Loading video stream..." phase after about a day or so of being connected to my device console.  The web browser (upon refreshing the page) consistently displayed a very brief pop-up message: "Failed to get EDID: error writing ctrl message: write unixpacket /var/run/jetkvm_ctrl.sock->@: use of closed network connection"   I'm pretty sure there shouldn't have been any closed connections, and this seems like an internal socket connection of some sort, but I'm not sure how one might know what to do with this otherwise.

Given the JetKVM wouldn't "come out" of this scenario and kept being stuck in the "Loading" loop... I pulled down the JetKVM "Web Terminal" and issued a "reboot" at the root # prompt and (remotely) rebooted it.  It was able to reconnect the screen where I left off and I was able to go on about my way.  Definitely weird.

**Comment by yezhao1984** [comment]
> I think i found a quick workaround but not really a fix, i think JetKVM devs needs to address this for a real fix.. When you see the screen showing "ICE gathering completed" for a while, click on refresh page once and wait for it to cycle thru. It should be able to show the stream. If this doesn't work the first time try hitting refresh again.

I have the same problem 。but refresh doesn't work for me

**Comment by MozkaGit** [comment]
I'm on Fedora 42 and it works everywhere (Chrome, Brave, Vivaldi, even Firefox Developer Edition) except on which is Firefox for Fedora (my main browser) and Firefox Flatpak.

My screen is stuck on "ICE Gathering completed". I tried to clear the cookies and refresh the page multiples times.

WebRTC is enabled in about:config.

![Image](https://github.com/user-attachments/assets/091db250-071e-4ed4-8d39-862eed1e941f)

I created a new Firefox profile and launch it with the CLI. The JetKVM web ui is working here. I tried to diff the config between both profiles, but I can't find the reason.

**Edit:**
After a lot of testing, I finally found a workaround that makes JetKVM work properly in Firefox (Fedora version). It turns out the issue was environment-related — when launching Firefox from the default desktop entry, something in the environment was preventing WebRTC from working correctly

Interestingly, JetKVM worked fine when I launched Firefox from the command line using `firefox --ProfileManager`, regardless of which profile I used. But when launching Firefox normally (e.g., via icon or default launcher), the issue came back — even with the same profile.

To fix it, I created a custom `.desktop` entry with an explicitly set environment and profile path. Placing it under `~/.local/share/applications/org.mozilla.firefox.desktop` overrides the system one.

Here’s the working `Exec` line:

```ini
Exec=bash -c 'MOZ_GMP_PATH=/path/to/gmp-gmpopenh264/system-installed PATH="/custom/path/bin:$PATH" firefox %u'
```

You can find the correct MOZ_GMP_PATH value on your system by running:

```bash
echo $MOZ_GMP_PATH
```

With this change, JetKVM now works perfectly in my main Firefox setup.

**Disclaimer:** I'm on **Fedora 42**. This workaround solved it for me, but I can't guarantee it will work for everyone.

**Comment by mcbrineellis** [comment]
Wanted to add my report of this issue as well.  It was my first time logging in for some weeks.
When I SSH in and do a reboot, the system comes back fine and video is working properly again.

**Troubleshooting Mode:**
`Resolution: 0x0, Video Size:300x150, Pointer: 0,0, USB State: configured, HDMI State: ready, keys:`

**Network:**
Unifi network.  Same issue when accessing directly with private IP or remotely using jetkvm.com

**Browsers attempted:**
Safari, Chrome, Firefox

**App version:**
0.4.1

**System version:**
0.2.4

**Comment by LaCocoRoco** [comment]
Thanks, as mentioned here a simple reboot did fix the problem. I would appreciate an reboot button in the interface.

**Comment by piratebatman** [comment]
DATA POINT: iOS Safari works when macOS browsers fail

Reporting an interesting finding that might help with debugging:

Behavior:

All macOS browsers FAIL: Firefox, Safari, Brave, Firefox ESR - all stuck at "Loading video stream..."
iOS Safari WORKS: Same device, same network, same JetKVM - video loads perfectly
Technical Details:

JetKVM firmware: Latest (May 2025)
Network: Same WiFi, same local IP access
WebRTC endpoints: Identical
Questions for other users:

Windows users: Does it work on Windows browsers but fail on macOS browsers on the same machine?
Linux users: Any similar patterns where mobile browsers work but desktop browsers fail?
Cross-platform testing: Has anyone tested the same JetKVM across multiple operating systems?
For developers:
This suggests the issue might be related to:

Different WebRTC implementations between platforms
User-agent specific server responses
Platform-specific STUN/TURN behavior
The fact that iOS Safari works provides a working baseline for comparison - the WebRTC connection can succeed, so this could help isolate what's different about desktop browser implementations.

Request: Can other users report their platform-specific results to help identify patterns?

**Comment by EA-ITINFRA** [comment]
Hi Everyone,

We ordered 3x devices, 2 of them work flawlessly, 1 of them has this issue where it's stuck at "loading video stream".

We tested it using the same windows computers, we tried, different browsers, resetting the config, nothing works we suspect this is hardware related.

**Comment by porkcharsui** [comment]
I ran into this issue recently after having no problems connecting to my JetKVM for ~1 month. After power cycling and trying multiple times, I too was stuck at the "loading video stream" step when connecting to the KVM.

Since I'm using the **ATX Control Board Extension**, on a whim I disconnected it and power cycled the JetKVM. On first try, it connected!

**Comment by dllz** [comment]
I have this issue as well. Getting this error as well 

![Image](https://github.com/user-attachments/assets/57e675d4-d4d3-4517-b9ac-30e7a5707c78)

**Comment by at-Duke** [comment]
I have the same issue. I bought this last month.

**Comment by kkygeek** [comment]
I was hoping it would be flawless but I see I'm not the only one with constant issues that makes it unusable for now. Let's hope it gets better, it's still early.

**Comment by ChrisDowning** [comment]
Just checking in to share that I still have not had any success with my JetKVM. To be honest I have given up on the device and moved on to other solutions, but since I never got around to turning off notifications for this issue I keep seeing others reporting positive outcomes from reboots, and so I occasionally try it again myself. No such luck, though I did capture this new error message when trying to change the EDID mode today:

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/a8597c84-e6e4-4756-9b00-d806b27cec63" />

**Comment by thedroidkid** [comment]
Seeing this on one of mine but the other one is just fine. I have to reboot every few days.

**Comment by AleksCee** [comment]
Has anyone get a connection running using [Pangolin](https://github.com/fosrl/pangolin ) as Proxy/Tunnel? The webui ist working but the Video connection not with the error from this issue.

**Comment by andras-tim** [comment]
> I have the same issue. I bought this last month.
Since this is an issue, maybe my comment will be off-topic, so sorry in advance.

But FYI, I got my JetKVMs very early via Kickstarter, and at the beginning I also had issues.

**Comment by andras-tim** [comment]
> Cant use the KVM because of this seriously it has been more than 5 months with this issue, makes no sense such issue remains.

_Let me share my success story here._

I also received my JetKVM quite early (via Kickstarter), and I had issues from the very beginning... but for some reason, I was at least able to use it in certain cases (e.g., from Firefox on Ubuntu and Chrome on Android), as [I reported later](https://github.com/jetkvm/kvm/issues/84#issuecomment-2789986555).

At that time, I enabled _SSH access_ to gather more information about the issue (this was the only change I made to the settings), and I rebooted the device several times, but nothing changed.

### However
I don't use my KVMs on a daily basis, but as I see now with version `App: 0.4.4, System: 0.2.4`, my devices just work from all browsers without any issues (I haven’t rebooted them for months).

While scrolling back up here, I found [another comment with a similar situation](https://github.com/jetkvm/kvm/issues/84#issuecomment-2944734708):
> Wanted to add my report of this issue as well. It was my first time logging in for some weeks.
> When I SSH in and do a reboot, the system comes back fine and video is working properly again.

... I also use a Unifi network, enabled SSH, ... maybe.

**Comment by stoff75** [comment]
I've had my JetKVM for a few weeks, it worked perfectly. Now I get this issue of stuck at "loading video stream". Fortunately for me it works after I powercycle the unit. But unfortunately that defeats the entire reason of having it!
I also noticed that it had gotten a firmware upgrade (App: 0.4.4, System: 0.2.4) as I can now enable https, but even with that off (as it has been since I received it) I get this issue.

**Comment by nofuturekid** [comment]
> I've had my JetKVM for a few weeks, it worked perfectly. Now I get this issue of stuck at "loading video stream". Fortunately for me it works after I powercycle the unit. But unfortunately that defeats the entire reason of having it! I also noticed that it had gotten a firmware upgrade (App: 0.4.4, System: 0.2.4) as I can now enable https, but even with that off (as it has been since I received it) I get this issue.

Second this - same behavior with App: 0.4.4 and System 0.2.4 on all of my JetKVMs.

**Comment by coreycdm** [comment]
> I've had my JetKVM for a few weeks, it worked perfectly. Now I get this issue of stuck at "loading video stream". Fortunately for me it works after I powercycle the unit. But unfortunately that defeats the entire reason of having it! I also noticed that it had gotten a firmware upgrade (App: 0.4.4, System: 0.2.4) as I can now enable https, but even with that off (as it has been since I received it) I get this issue.

Came here to post the same.  I had no issues initially with either lan or cloud console connection.  Now, the unit (same app/system versions) gets stuck loading until I power cycle.

As a temporary workaround, I have the power brick plugged into a smart plug that power cycles once per day overnight.  So far, that seems to have helped, but it's certainly not how the product should work.

**Comment by nofuturekid** [comment]
> > I've had my JetKVM for a few weeks, it worked perfectly. Now I get this issue of stuck at "loading video stream". Fortunately for me it works after I powercycle the unit. But unfortunately that defeats the entire reason of having it! I also noticed that it had gotten a firmware upgrade (App: 0.4.4, System: 0.2.4) as I can now enable https, but even with that off (as it has been since I received it) I get this issue.
> 
> Came here to post the same. I had no issues initially with either lan or cloud console connection. Now, the unit (same app/system versions) gets stuck loading until I power cycle.
> 
> As a temporary workaround, I have the power brick plugged into a smart plug that power cycles once per day overnight. So far, that seems to have helped, but it's certainly not how the product should work.

You can SSH into the JetKVM or enable the Web terminal and reboot the JetKVM from there. But anyways, it's uncomfortable and it should work without such workarounds.

Edit: For now the latest beta seems to have fixed the issue, though I don't know which commit addresses this.

**Comment by coreycdm** [comment]
> > > I've had my JetKVM for a few weeks, it worked perfectly. Now I get this issue of stuck at "loading video stream". Fortunately for me it works after I powercycle the unit. But unfortunately that defeats the entire reason of having it! I also noticed that it had gotten a firmware upgrade (App: 0.4.4, System: 0.2.4) as I can now enable https, but even with that off (as it has been since I received it) I get this issue.
> > 
> > 
> > Came here to post the same. I had no issues initially with either lan or cloud console connection. Now, the unit (same app/system versions) gets stuck loading until I power cycle.
> > As a temporary workaround, I have the power brick plugged into a smart plug that power cycles once per day overnight. So far, that seems to have helped, but it's certainly not how the product should work.
> 
> You can SSH into the JetKVM or enable the Web terminal and reboot the JetKVM from there. But anyways, it's uncomfortable and it should work without such workarounds.
> 
> Edit: For now the latest beta seems to have fixed the issue, though I don't know which commit addresses this.

How do you reboot from the cloud console?  I can't find that option anywhere.

And yeah, I know SSH is an option...but simplifying access from outside my network is one of the main reasons I went with this device!

**Comment by nofuturekid** [comment]
You have to enable "Developer Options" in the settings and then you will get a "Web Terminal" in "top menu" above the virtual screen. This one then will drop you into a shell of the JetKVM and there you just 'reboot'.

![Image](https://github.com/user-attachments/assets/96ca9e7c-2be1-45ba-886e-ab7c8917c267)

**Comment by jorgii** [comment]
I had the same issue but it seems it got fixed after I set "Turn off display after" to "never" in the "Hardware" section of settings.

**Comment by nofuturekid** [comment]
> I had the same issue but it seems it got fixed after I set "Turn off display after" to "never" in the "Hardware" section of settings.

I'm pretty sure had this disabled and I don't see any relation between the touch display and the video stream.

Still the video stream should not stop functioning when this timeout is set.

Good you found another workaround.

**Comment by jorgii** [comment]
> > I had the same issue but it seems it got fixed after I set "Turn off display after" to "never" in the "Hardware" section of settings.
> 
> I'm pretty sure had this disabled and I don't see any relation between the touch display and the video stream.
> 
> Still the video stream should not stop functioning when this timeout is set.
> 
> Good you found another workaround.

That's a good point. I will revert the setting to see whether it is a coincidence.

**Comment by thedroidkid** [comment]
I have a feeling this is now fixed in 0.4.5 posted 6 hours go.


Restart jetkvm_native automatically by @ym in https://github.com/jetkvm/kvm/pull/629

This PR adds functionality to automatically restart the jetkvm_native binary if it terminates unexpectedly.

Introduces locking around binary start-up via startNativeBinaryWithLock.
Implements functions (restartNativeBinary and superviseNativeBinary) to monitor and restart the binary.
Updates ExtractAndRunNativeBin to run a supervisor loop that ensures the binary is running.

**Comment by k4emic** [comment]
I also got stuck on "ICE Gathering completed" on fedora 42 + firefox 139. Works fine in chrome and librewolf.

I had success fixing this by enabling `media.webrtc.hw.h264.enabled` in `about:config`.

**Comment by ctreiser** [comment]
I am running ubuntu and keep having this issue when I leave the machine alone for a period of time longer then an hour. I did have some limited sucess with using the "wake on lan" function, but I rebooted the linux machine and it went back to the NO HDMI Detected. 
I tried connecting from the local network, same error, switched back to cloud and now I have the desktop showing.

**Comment by alexisgahon** [comment]
Just received mine, so sad it get stuck on Loading Video Stream ... (no matter the client ...)
Wanted to use on my Reolink DVR

**Comment by mygrexit** [comment]
same problem.

**Comment by Coder84619** [comment]
Yup it's broken for me too. Highly disappointing.

**Comment by SvenFinn** [comment]
I've encountered a similar issue where the KVM gets stuck at **"ICE gathering complete"**, but only on one specific device. Looking at the WebSocket signaling messages, I saw the following:

```
Server → Client: {"data":{"deviceVersion":"0.4.6"},"type":"device-metadata"}
Client → Server: {"type":"offer","data":{"sd":"..."}}
Server → Client: {"error":{}}
```

So the server seems to detect some error, but it just sends an empty error object without any useful details.

After this point, the client continues sending ICE candidates:

```
Client → Server: {"type":"new-ice-candidate","data":{"candidate":"candidate:0 1 UDP ...","sdpMLineIndex":0,"sdpMid":"0",...}}
Client → Server: {"type":"new-ice-candidate","data":{"candidate":"candidate:1 1 TCP ...","sdpMLineIndex":0,"sdpMid":"0",...}}
Client → Server: {"type":"new-ice-candidate","data":{"candidate":"candidate:0 2 UDP ...","sdpMLineIndex":0,"sdpMid":"0",...}}
Client → Server: {"type":"new-ice-candidate","data":{"candidate":"candidate:1 2 TCP ...","sdpMLineIndex":0,"sdpMid":"0",...}}
Client → Server: {"type":"new-ice-candidate","data":{"candidate":"candidate:0 1 UDP ...","sdpMLineIndex":1,"sdpMid":"1",...}}
Client → Server: {"type":"new-ice-candidate","data":{"candidate":"candidate:1 1 TCP ...","sdpMLineIndex":1,"sdpMid":"1",...}}
```

But nothing comes back from the server after that, and the connection never completes.

**Cause and workaround:**
After some digging, I found that **IPv6 was disabled** on this device. Re-enabling IPv6 immediately resolved the issue — KVM connected as expected.

Would be great if the server returned a more descriptive error when this happens. Right now it silently fails, which makes it harder to debug.

**Comment by taranjlu** [comment]
I am also having this issue, but it only shows up when I am trying to remotely connect via tailscale. If I am on my local LAN, I am able to use my tailnet domain just fine and I am able to get to the web gui successfully (tested on several devices). However, if I disconnect and use data on my phone, I get to the login screen, but it fails to load the video stream and after a few seconds, I get the error page that says "Connection Issue Detected." Reconnecting to my LAN allows my phone to access the web gui just fine.

Edit: I also just tested tethering my phone to my laptop and was able to get through to the web gui with the video feed using using Firefox, so at least in my case, the issue seems to only show up for mobile (iOS) browsers (Brave, Safari, and Chrome) when not on my LAN.

**Comment by alexisgahon** [comment]
> Just received mine, so sad it get stuck on Loading Video Stream ... (no matter the client ...) Wanted to use on my Reolink DVR

I changed the resolution on my Reolink DVR to 1920x1080 instead of 3840*2160 and it's working now.
Just the mouse is a bit buggy.

**Comment by evilphish** [comment]
Same problem here with a brand new unit I just received. Did a firmware update so I am now at:
App: 0.4.8
System: 0.2.5

Using Firefox 143.0.1

**Network setup:** Unifi network hardware, jetKVM and clients that show the error message are all on the same subnet. No cloud, no NAT, no firewall involved.

**Data below video stream window:**

<img width="970" height="36" alt="Image" src="https://github.com/user-attachments/assets/e6f4f77d-c406-4026-9f7f-77fd51c21a71" />

**Tested with:** Firefox (Version see above) and Chrome on desktop Linux Mint and Android

**Comment by Mazyod** [comment]
I've used JetKVM since March 2025 (Kickstarter) without much issues, but this week (Dec. ~20th) I decided to unplug the HDMI and connect my monitor directly for a bit. After that, I hit this issue for the first time.

I tried unplugging the system, reboot from the web dashboard, nothing seemed to work. Finally, tried the `reboot` command from the web terminal, and that finally solved it... No idea why that would be different than the other power cycle methods I've tried.

**Comment by SebDominguez** [comment]
Mine was working flawlessly until one day (maybe after 5 month of use) it was stuck at “initializing” on the oled screen and after unplugging it now I have NO HDMI signal detected.

**Comment by pearls-of-agrippa** [comment]
I ran into the same problem seemingly after a power loss from PG&E.  It may have had nothing to do with it, but I found a mitigation:  I went to the screen that showed the HDMI error, and pulled up the virtual keyboard.  I picked 't' randomly, pressed it rapidly about 10 times.  And lo!  the screen popped up.  I cannot explain it, but it worked and I have my HDMI connection back after a couple of months.  I'm very curious if this works for anyone else.

**Comment by SebDominguez** [comment]
> I ran into the same problem seemingly after a power loss from PG&E. It may have had nothing to do with it, but I found a mitigation: I went to the screen that showed the HDMI error, and pulled up the virtual keyboard. I picked 't' randomly, pressed it rapidly about 10 times. And lo! the screen popped up. I cannot explain it, but it worked and I have my HDMI connection back after a couple of months. I'm very curious if this works for anyone else.

unfortunately it didn't worked for me

**Comment by adamshiervani** [comment]
Will close this as this has inflated to a mega issue. If you land here, and have issues please refer to our [Troubleshooting Guide](https://jetkvm.com/docs/getting-started/troubleshooting#loading-video-stream-issue), which should include many of the advice found in the thread. 

If that doesn't solve your problem, feel free to open a new issue with specific details about your setup and problem.

**Comment by samJwitt** [comment]
> Will close this as this has inflated to a mega issue. If you land here, and have issues please refer to our [Troubleshooting Guide](https://jetkvm.com/docs/getting-started/troubleshooting#loading-video-stream-issue), which should include many of the advice found in the thread.
> 
> If that doesn't solve your problem, feel free to open a new issue with specific details about your setup and problem.

The Troubleshooting Guide links back to here, so that's circular. Is there going to be a fix?

**Comment by mygrexit** [comment]
Nothing works for me.
I'm stuck at "Loading video stream..." in Firefox and in Chromium. I tried all the suggested fixes.

Would be great if you could stop pointing us towards outdated FAQs and actually try to fix the issue @adamshiervani

**Comment by SebDominguez** [comment]
Is there a way to install the original firmware from the first Kickstarter delivery batch?

**Comment by samJwitt** [comment]
@adamfeldman can this please be re-opened? It was never fixed, and I'm not sure why it being a "mega issue" resulted in it being closed.

**Comment by deloss-s** [comment]
Same problem, it is fixed via entering & exiting fullscreen mode

**Comment by bobbolous** [comment]
Was stuck at  "Loading video stream..." using Firefox (LAN via local IP). Sometimes it works immediately sometimes not. When I was stuck I opened a Edge window in parallel to access and the stream imediately worked. Also as I switched back to Firefox.

For reference and according to the troubleshooting guide
```
Version App: 0.5.8 (most recent)
Version System: 0.2.8 (most recent)

media.peerconnection.enabled = true
media.webrtc.hw.h264.enabled = true
OpenH264 ("OpenH264-Videocodec zur Verfügung gestellt von Cisco Systems, Inc.") -> enabled
```
Using Private Mode in Firefox (although all Plugins enabled) also immediately establishes the stream.
